# Generated by Django 5.1 on 2024-09-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_time_moodentry_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='ItemEntry',
        ),
    ]
